feat: asset에 대해서 tuist 내장 swiftgen 사용하도록 함
Team-Archive/PhotoArchive-iOS pull request #1
Opened 2024-02-07 15:22 UTC by luboolu

- asset을 tuist 내장 swiftgen으로 관리할 수 있게 함

2024-02-12 00:55 UTC, HanweeeeLee requested changes
안녕하세요 진영님! 설 잘 보내셨나요? 
시골에 다녀오느라 리뷰가 늦었네요. 죄송합니다 🥲🙇

올려주신 코드 살펴보았는데요! 

전반적으로 궁금한게 있습니다!

현재 SwiftGen을 사용해 에셋을 빌드시점에 코드로 생성하고있는데요, 
이걸 Tuist에 내장되어있는 코드생성으로 바꾸면서 tuist generate 시점으로 코드 생성시점이 바뀐것 같습니다!

이걸 빌드 시점에 코드가 생성되도록 바꿀 수 있는 방법이 없을까요?

2024-02-13 14:24 UTC, luboolu commented
한위님 안녕하세요! 새해 복 많이 받으세요:)
아닙니다 저도 바빠서 바로바로 확인 못하고 있었네요ㅎㅎㅠ

저도 그 부분에 대해서 서치를 진행해보았는데, 딱히 마땅한 해답은 얻지 못했습니다..
Tuist git issue에 같은 요구사항이 open으로 등록되어 있긴 합니다만 당장 바꿀 수 있는 방법은 없을거 같아요.
Tuist 내부에서 어떻게 SwiftGen을 실행하는건지 파보고 있었습니다..

+) 혹시 tuist 4.0 버전 사용해보셨나요? tuist fetch 명령어가 변경됐다는데, 제대로 동작 안해서 회사 환경 셋팅 할때 애먹었네요😭

2024-02-14 03:11 UTC, HanweeeeLee commented
안녕하세요 진영님! 
저도 여기저기 수소문하고 찾아봤는데, 딱히 방법이 뾰족히 있지는 않는것 같더라구요. 

결국 빌드 시점에 동작을 시키기위해 SwiftGen을 쓰느냐, tuist generate시점에 동작을 시키고 tuist것을 쓰느냐 
취향차이 같습니다.🙂

개인적인 취향으로는 빌드시점이긴한데,  tuist generate시점으로 써본적은 없어서 

그러면 진영님이 PR올려주신 것 처럼 tuist generate시점에 사용해보는것도 저에게 있어서는 좋은 경험이 될 것 같아요!

작업해주시느라 고생하셨습니다. 🙇🏻‍♂️

2024-02-14 03:12 UTC, HanweeeeLee approved these changes

2024-02-17 11:57 UTC, merged